const IMG='https://images.unsplash.com/';
const seedAlbums=[
 {id:'90',era:'90年代',title:'旧日晴光',desc:'胶片里的夏天',cover:IMG+'photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1000&q=85',photos:[['海风和白墙',IMG+'photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=85'],['下午四点',IMG+'photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1000&q=85']]},
 {id:'00',era:'00年代',title:'城市漫游',desc:'去没有去过的地方',cover:IMG+'photo-1494526585095-c41746248156?auto=format&fit=crop&w=1000&q=85',photos:[['窗外的城市',IMG+'photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=1000&q=85'],['山脊线',IMG+'photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=85']]},
 {id:'10',era:'10年代',title:'植物图鉴',desc:'一小块绿色的秘密',cover:IMG+'photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=1000&q=85',photos:[['叶片的纹理',IMG+'photo-1515549832467-8783363e19b6?auto=format&fit=crop&w=1000&q=85'],['雨后的花园',IMG+'photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=1000&q=85']]},
 {id:'20',era:'20年代',title:'当下时刻',desc:'生活正在发生',cover:IMG+'photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=85',photos:[['柔软日常',IMG+'photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1000&q=85'],['周末光线',IMG+'photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1000&q=85']]},
 {id:'notes',era:'随手记',title:'风吹过的时候',desc:'一些未分类的片段',cover:IMG+'photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1000&q=85',photos:[['远方',IMG+'photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1000&q=85'],['光落下来',IMG+'photo-1511497584788-876760111969?auto=format&fit=crop&w=1000&q=85']]},
 {id:'people',era:'人物',title:'在场的人',desc:'关于相遇和拥抱',cover:IMG+'photo-1504593811423-6dd665756598?auto=format&fit=crop&w=1000&q=85',photos:[['微笑之后',IMG+'photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1000&q=85'],['一起走走',IMG+'photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1000&q=85']]}
];
seedAlbums.push(
 {id:'garden',era:'自然',title:'花园深处',desc:'叶影与微风',cover:IMG+'photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=1000&q=85',photos:[['绿色时刻',IMG+'photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=85']]},
 {id:'seasons',era:'四季',title:'四季信笺',desc:'天气写下的信',cover:IMG+'photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1000&q=85',photos:[['春日来信',IMG+'photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=1200&q=85']]},
 {id:'small-things',era:'日常',title:'小小事情',desc:'值得被记住的瞬间',cover:IMG+'photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1000&q=85',photos:[['桌边光线',IMG+'photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1200&q=85']]}
);
const defaultSettings={loginTitle:'进入花园',loginDescription:'',homeTitle:'Things grow in the garden.',homeSubtitle:'一个持续生长的私人影像档案。按年代、地点和心情浏览，也可以把你此刻的照片放进来。',searchTitle:'Let the garden guide you.',backgroundVideo:'',backgroundMusic:'',sizes:{loginTitle:23,homeTitle:76,homeSubtitle:16,searchTitle:28,photoDescription:14}};
let albums=JSON.parse(localStorage.getItem('gardenAlbums')||'null')||seedAlbums;seedAlbums.forEach(seed=>{if(!albums.some(album=>album.id===seed.id))albums.push(seed)});localStorage.setItem('gardenAlbums',JSON.stringify(albums));
let settings={...defaultSettings,...JSON.parse(localStorage.getItem('gardenSettings')||'{}')};settings.sizes={...defaultSettings.sizes,...(settings.sizes||{})};
let role=null,activeAlbum=null,era='全部';const app=document.querySelector('#app');
const save=()=>localStorage.setItem('gardenAlbums',JSON.stringify(albums));const saveSettings=()=>localStorage.setItem('gardenSettings',JSON.stringify(settings));
function mediaMarkup(){return settings.backgroundVideo?`<div class="media-window"><video src="${settings.backgroundVideo}" autoplay muted loop playsinline controls></video><span class="media-badge">ADMIN VIDEO · LOOP</span></div>`:`<div class="media-window media-empty"><span>管理员上传的视频将在这里循环播放</span></div>`}
const mediaObserver=new MutationObserver(()=>{const stage=document.querySelector('.hero-stage');if(stage&&!stage.dataset.mediaReady){stage.dataset.mediaReady='1';stage.innerHTML=mediaMarkup();stage.classList.add('media-stage')}document.querySelectorAll('.photo-grid .photo-card>img').forEach(image=>image.removeAttribute('onclick'))});mediaObserver.observe(app,{childList:true,subtree:true});
const toast=msg=>{let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.append(t)}t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
function header(){return `<header class="topbar"><button class="brand" onclick="showHome()"><span class="brand-mark">it</span><span>In the garden<small>花园里 / VISUAL ARCHIVE</small></span></button><div class="nav-actions">${role==='admin'?'<button class="ghost-btn" onclick="adminEdit()">编辑设置</button>':''}<button class="icon-btn" title="退出" onclick="logout()">↗</button></div></header>`}
function login(){app.innerHTML=`<main class="login-view"><div class="login-grid"><section class="login-copy"><div class="eyebrow">A living visual archive · 2024—2026</div><h1>In the<br><i>garden.</i></h1><p>照片会留下来，像风穿过树叶时的声音。欢迎进入一个由日常、光线和记忆组成的小小花园。</p></section><section><div class="login-art"><img class="reference" src="assets/garden-reference.jpg" alt="花园里的猫与鸟"/><span class="stage-label">IMAGE 01 / GARDEN REFERENCE</span></div><div class="login-card"><h2 style="font-size:${settings.sizes.loginTitle}px">${settings.loginTitle}</h2>${settings.loginDescription?`<p>${settings.loginDescription}</p>`:''}<div class="code-field"><input id="access-code" type="password" autocomplete="current-password" placeholder="请输入访问码" aria-label="访问码" onkeydown="if(event.key==='Enter')enter()"/><button onclick="enter()">进入 ↗</button></div><div class="recent"><div class="recent-title"><span>近期浏览</span><span>LIVE FEED</span></div><div class="ticker"><div class="ticker-track"><span>✦ 新增相册「风吹过的时候」</span><span>✦ 更新封面 · 植物图鉴</span><span>✦ 新照片 · 柔软日常</span></div></div></div></div></section></div></main>`}
function enter(){const c=document.querySelector('#access-code').value.trim();if(c==='688'){role='admin';showHome()}else if(c==='8866'){role='user';showHome()}else toast('访问码不正确，请重试')}
function showHome(){activeAlbum=null;app.innerHTML=header()+`<main class="page">${settings.backgroundVideo?`<video class="site-video" src="${settings.backgroundVideo}" autoplay muted loop playsinline></video>`:''}<section class="home-hero"><div><div class="eyebrow">Welcome to the archive / 2024—2026</div><h1 style="font-size:${settings.sizes.homeTitle}px">${settings.homeTitle}</h1><p style="font-size:${settings.sizes.homeSubtitle}px">${settings.homeSubtitle}</p></div><div class="hero-stage"><img src="assets/garden-reference.jpg" alt="猫与鸟的花园"/><span class="stage-label">TODAY'S VIEW · 01</span><button class="stage-play" onclick="toast('视频预览将在云端媒体接入后播放')">▶</button></div></section><section class="search-showcase"><div class="search-heading" style="font-size:${settings.sizes.searchTitle}px">${settings.searchTitle}</div><div class="search-art"><img class="bird bird-left" src="assets/garden-reference.jpg" alt="鸽子装饰"/><img class="bird bird-mid" src="assets/garden-reference.jpg" alt="麻雀装饰"/><img class="bird bird-right" src="assets/garden-reference.jpg" alt="鸟装饰"/><img class="cat-cut" src="assets/garden-reference.jpg" alt="猫咪装饰"/><div class="search-wrap"><span>⌕</span><input id="search" placeholder="搜索照片或相册名称" oninput="renderAlbums()"/><button onclick="renderAlbums()">Search</button></div></div></section><div class="toolbar"><div class="music"><button onclick="toggleMusic(this)">♫</button><span>Garden radio</span><small>OFF</small></div></div><nav class="era-nav">${['90年代','00年代','10年代','20年代'].map(x=>`<button class="${era===x?'active':''}" onclick="setEra('${x}')">${x}</button>`).join('')}</nav><div class="section-head"><div><h2>相册入口</h2><p>COLLECTED MOMENTS / ${albums.length} ALBUMS</p></div>${role==='admin'?'<button class="ghost-btn" onclick="newAlbum()">＋ 新建相册</button>':''}</div><div id="album-grid" class="album-grid"></div></main>`;renderAlbums()}
function setEra(x){era=x;showHome()}
function directoryLabels(){return [...new Set(albums.map(a=>a.era).filter(Boolean))].slice(0,4)}
function renderAlbums(){const q=(document.querySelector('#search')?.value||'').toLowerCase();const list=albums.filter(a=>(`${a.title}${a.desc}`.toLowerCase().includes(q))&&(era==='全部'||era===a.era));const grid=document.querySelector('#album-grid');if(!grid)return;grid.innerHTML=list.length?list.map(a=>`<article class="album-card" onclick="openAlbum('${a.id}')"><div class="album-cover"><img src="${a.cover}" alt="${a.title}"/><span class="album-era ${role==='admin'?'editable-directory':''}" ${role==='admin'?`contenteditable="true" spellcheck="false" onclick="event.stopPropagation()" onblur="updateAlbumText('${a.id}','era',this.textContent)" onkeydown="if(event.key==='Enter'){event.preventDefault();this.blur()}`:''}>${a.era}</span><button class="cover-edit" title="编辑封面" onclick="event.stopPropagation();changeAlbumCover('${a.id}')">✎</button></div><div class="album-info"><div><h3 contenteditable="true" spellcheck="false" onclick="event.stopPropagation()" onblur="updateAlbumText('${a.id}','title',this.textContent)" onkeydown="if(event.key==='Enter'){event.preventDefault();this.blur()}">${a.title}</h3><p contenteditable="true" spellcheck="false" onclick="event.stopPropagation()" onblur="updateAlbumText('${a.id}','desc',this.textContent)">${a.desc}</p></div><span class="arrow">↗</span></div></article>`).join(''):'<div class="empty">没有找到匹配的相册。</div>'}
function updateAlbumText(id,field,value){const album=albums.find(a=>a.id===id);if(!album)return;const clean=value.trim();if(!clean)return;album[field]=clean;save();if(field==='era'){era='全部';showHome();toast('目录标签已保存并同步')}else toast('相册文字已保存')}
function changeAlbumCover(id){const album=albums.find(a=>a.id===id);if(!album)return;const input=document.createElement('input');input.type='file';input.accept='image/*';input.onchange=()=>readFile(input,(src)=>{album.cover=src;save();renderAlbums();toast('相册封面已保存')});input.click()}
function openAlbum(id){activeAlbum=albums.find(a=>a.id===id);if(!activeAlbum)return;app.innerHTML=header()+`<main class="page"><div class="detail-head"><div><button class="ghost-btn" onclick="showHome()">← 返回花园</button><h1>${activeAlbum.title}</h1><p>${activeAlbum.desc} · ${activeAlbum.era}</p></div><div class="eyebrow">${String(activeAlbum.photos.length).padStart(2,'0')} IMAGES</div></div><div class="gallery">${activeAlbum.photos.map((p,i)=>`<div class="gallery-card" onclick="openPhoto(${i})"><img src="${p[1]}" alt="${p[0]}"/><span>${p[0]} · 点击查看原图</span></div>`).join('')}<button class="upload-frame" onclick="addPhoto()">＋ 添加照片</button></div><div class="section-head"><div><h2>照片展示</h2><p>点击相框查看原图，所有上传内容会保存</p></div><span><button class="primary-btn" onclick="addPhoto()">＋ 上传照片</button>${role==='admin'?'<button class="ghost-btn" onclick="changeCover()">更换封面</button>':''}</span></div><div class="photo-grid">${activeAlbum.photos.map((p,i)=>`<article class="photo-card"><img onclick="openPhoto(${i})" src="${p[1]}" alt="${p[0]}"/><div class="photo-caption"><input style="font-size:${settings.sizes.photoDescription}px" value="${p[0]}" onchange="updateCaption(${i},this.value)"/><div class="photo-actions"><small>PHOTO ${String(i+1).padStart(2,'0')}</small>${role==='admin'?`<button class="ghost-btn" onclick="deletePhoto(${i})">删除</button>`:''}</div></div></article>`).join('')}</div></main>`}
function openPhoto(index){const p=activeAlbum?.photos[index];if(!p)return;const modal=document.createElement('div');modal.className='photo-modal';modal.innerHTML=`<div class="photo-modal-inner"><button class="modal-close" aria-label="关闭">×</button><img src="${p[1]}" alt="${p[0]}"/><div class="modal-actions"><strong>${p[0]}</strong><a class="ghost-btn" href="${p[1]}" download="${p[0]||'garden-photo'}">下载原图</a><button class="primary-btn" id="replace-photo">替换照片</button></div></div>`;modal.addEventListener('click',e=>{if(e.target===modal||e.target.classList.contains('modal-close'))modal.remove()});modal.querySelector('#replace-photo').onclick=()=>{const input=document.createElement('input');input.type='file';input.accept='image/*';input.onchange=()=>readFile(input,(src,file)=>{activeAlbum.photos[index]=[file.name.replace(/\.[^.]+$/,''),src];save();modal.remove();openAlbum(activeAlbum.id);toast('原图已替换并保存')});input.click()};document.body.append(modal)}
function updateCaption(i,v){if(!role){toast('请先登录');return}activeAlbum.photos[i][0]=v;save();toast('照片描述已保存')}
function deletePhoto(i){if(role!=='admin')return;activeAlbum.photos.splice(i,1);save();openAlbum(activeAlbum.id);toast('照片已删除')}
async function uploadToSupabase(file){const cfg=window.SUPABASE_CONFIG;if(!cfg)return null;const path=`photos/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const response=await fetch(`${cfg.url}/storage/v1/object/garden-media/${path}`,{method:'POST',headers:{apikey:cfg.anonKey,Authorization:`Bearer ${cfg.anonKey}`,'Content-Type':file.type||'application/octet-stream','x-upsert':'true'},body:file});if(!response.ok)throw new Error('云端上传失败');return `${cfg.url}/storage/v1/object/public/garden-media/${path}`}
function addPhoto(){if(!role){toast('请先登录后上传照片');return}const input=document.createElement('input');input.type='file';input.accept='image/*';input.multiple=true;input.onchange=async()=>{const files=Array.from(input.files||[]);if(!files.length)return;toast('正在上传到云端...');for(const file of files){try{const remote=await uploadToSupabase(file);const reader=new FileReader();await new Promise(resolve=>{reader.onload=()=>{activeAlbum.photos.push([file.name.replace(/\.[^.]+$/,''),remote||reader.result]);resolve()};reader.readAsDataURL(file)});if(remote&&window.SUPABASE_CONFIG){await fetch(`${window.SUPABASE_CONFIG.url}/garden_photos`,{method:'POST',headers:{apikey:window.SUPABASE_CONFIG.anonKey,Authorization:`Bearer ${window.SUPABASE_CONFIG.anonKey}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({album_id:activeAlbum.id,title:file.name,file_url:remote})})}}catch(error){toast('云端上传失败，已保留本地副本')}}save();openAlbum(activeAlbum.id);toast(`已上传 ${files.length} 张照片`) };input.click()}
function readFile(input, done){const file=input.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>done(reader.result,file);reader.readAsDataURL(file)}
function uploadPhotoFile(input){if(role!=='admin')return;readFile(input,(src,file)=>{activeAlbum.photos.push([file.name.replace(/\.[^.]+$/,''),src]);save();openAlbum(activeAlbum.id);toast('相片已上传并保存')})}
function changeCover(){if(role!=='admin')return;const input=document.createElement('input');input.type='file';input.accept='image/*';input.onchange=()=>readFile(input,(src)=>{activeAlbum.cover=src;save();openAlbum(activeAlbum.id);toast('相册封面已更换并保存')});input.click()}
async function uploadMedia(kind,input){if(role!=='admin')return;const file=input.files?.[0];if(!file)return;try{toast('正在上传到云端...');const remote=await uploadToSupabase(file);settings[kind]=remote||await new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsDataURL(file)});saveSettings();if(window.SUPABASE_CONFIG){await fetch(`${window.SUPABASE_CONFIG.url}/garden_settings`,{method:'POST',headers:{apikey:window.SUPABASE_CONFIG.anonKey,Authorization:`Bearer ${window.SUPABASE_CONFIG.anonKey}`,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates'},body:JSON.stringify({id:'site',value:settings})})}showHome();toast((kind==='backgroundMusic'?'音乐':'视频')+'已上传并保存') }catch(error){toast('云端上传失败，请重试')}}
function newAlbum(){if(role!=='admin'){toast('只有管理员可以创建相册');return}const title=prompt('相册名称');if(!title)return;albums.push({id:Date.now().toString(),era:'20年代',title,desc:'新的记忆正在发生',cover:IMG+'photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1000&q=85',photos:[]});save();showHome();toast('相册已创建')}
function adminEdit(){if(role!=='admin')return;app.insertAdjacentHTML('beforeend',`<div class="admin-panel expanded"><div><strong>内容与媒体设置</strong><p>媒体与文字字段保存至浏览器数据层</p></div><div class="admin-fields"><label>登录标题<input id="s-loginTitle" value="${settings.loginTitle}"></label><label>登录说明<input id="s-loginDescription" value="${settings.loginDescription}"></label><label>首页主标题<input id="s-homeTitle" value="${settings.homeTitle}"></label><label>首页副标题<input id="s-homeSubtitle" value="${settings.homeSubtitle}"></label><label>搜索区标题<input id="s-searchTitle" value="${settings.searchTitle}"></label><label>首页标题字号(px)<input type="number" id="s-homeSize" value="${settings.sizes.homeTitle}"></label><label>副标题字号(px)<input type="number" id="s-subSize" value="${settings.sizes.homeSubtitle}"></label><label>搜索标题字号(px)<input type="number" id="s-searchSize" value="${settings.sizes.searchTitle}"></label><label>照片描述字号(px)<input type="number" id="s-photoSize" value="${settings.sizes.photoDescription}"></label><label class="file-label">上传背景视频<input type="file" accept="video/*" onchange="uploadMedia('backgroundVideo',this)"></label><label class="file-label">上传背景音乐<input type="file" accept="audio/*" onchange="uploadMedia('backgroundMusic',this)"></label></div><div class="admin-actions"><button onclick="saveAdminSettings()">保存设置</button><button class="ghost-btn" onclick="document.querySelector('.admin-panel.expanded').remove()">取消</button></div></div>`)}
function saveAdminSettings(){settings.loginTitle=document.querySelector('#s-loginTitle').value;settings.loginDescription=document.querySelector('#s-loginDescription').value;settings.homeTitle=document.querySelector('#s-homeTitle').value;settings.homeSubtitle=document.querySelector('#s-homeSubtitle').value;settings.searchTitle=document.querySelector('#s-searchTitle').value;settings.sizes.homeTitle=+document.querySelector('#s-homeSize').value||76;settings.sizes.homeSubtitle=+document.querySelector('#s-subSize').value||16;settings.sizes.searchTitle=+document.querySelector('#s-searchSize').value||28;settings.sizes.photoDescription=+document.querySelector('#s-photoSize').value||14;saveSettings();document.querySelector('.admin-panel.expanded').remove();showHome();toast('管理员设置已保存')}
function toggleMusic(btn){const on=btn.nextElementSibling.nextElementSibling;const audio=document.querySelector('#garden-audio')||new Audio(settings.backgroundMusic);audio.loop=true;if(on.textContent==='OFF'){if(!settings.backgroundMusic){toast('请先由管理员上传背景音乐');return}audio.play();on.textContent='ON';btn.style.background='var(--lime)'}else{audio.pause();on.textContent='OFF';btn.style.background='var(--blue)'}toast(on.textContent==='ON'?'背景音乐已开启':'背景音乐已关闭')}
document.addEventListener('click',()=>{if(settings.backgroundMusic&&!window.gardenAudioStarted){const audio=document.querySelector('#garden-audio')||new Audio(settings.backgroundMusic);audio.loop=true;audio.play().then(()=>{window.gardenAudioStarted=true}).catch(()=>{})}},{once:false});
function logout(){role=null;era='全部';login()}
login();
